site:
  tab: Miunaã®åšå®¢
  title: Miuna
  description: ğŸŒ¸ è½»ç›ˆã€ä¼˜é›…ã€çº¯å‡€ â€”â€” ç”¨æ–‡å­—ä¸å›¾ç‰‡è®°å½•ç”Ÿæ´»ä¸åˆ›æ„
  language: zh
  favicon: /favicon.ico
  theme:
    light: garden
    dark: dracula
    code: github-dark
  date_format: ddd MMM DD YYYY
  blog:
    pageSize: 8
  banner:
    enableRandom: true
    randomUrl: https://pic.000.moe/random
    randomCount: 5
    height: 60vh
    images:
      - https://pic.000.moe/random
  icp: èŒICPå¤‡20251991å·
  icp_link: https://icp.gov.moe/?keyword=20251991
  pages:
    home:
      title: Miuna's Blog
      subtitle: èè‰æœ‰ä¸‰å¥½ï¼Œèº«å¨‡ä½“å¼±æ˜“æ¨å€’
      typewriterTexts:
        - âœ¨ èè‰æœ‰ä¸‰å¥½ï¼Œèº«å¨‡ä½“å¼±æ˜“æ¨å€’
        - âš¡ ä½ æŒ‡å°–è·ƒåŠ¨çš„ç”µå…‰ï¼Œæ˜¯æˆ‘æ­¤ç”Ÿä¸ç­çš„ä¿¡ä»°
        - ğŸ’« æ­¤ç”Ÿæ— æ‚”å…¥ä¸œæ–¹ï¼Œæ¥ä¸–æ„¿ç”Ÿå¹»æƒ³ä¹¡
        - ğŸ‰ ä½ æ‰€çƒ­çˆ±çš„ï¼Œå°±æ˜¯ä½ çš„ç”Ÿæ´»ã€‚
        - ğŸˆ æˆ‘ä»¬æ‰€ç»å†çš„æ¯ä¸ªå¹³å‡¡çš„æ—¥å¸¸ï¼Œä¹Ÿè®¸å°±æ˜¯è¿ç»­å‘ç”Ÿçš„å¥‡è¿¹
    friend:
      title: å‹äººå¸
      subtitle: è®°å½•é‚£äº›çè´µçš„å‹è°Šï¼Œåˆ†äº«å½¼æ­¤çš„æ•…äº‹
    about:
      title: å…³äºæˆ‘
      subtitle: ä¸€ä¸ªçƒ­çˆ±ç”Ÿæ´»ä¸æŠ€æœ¯çš„æ™®é€šäººï¼
    navigation:
      title: ç½‘ç«™å¯¼èˆª
      subtitle: æ”¶è—çš„å¸¸ç”¨ç½‘ç«™å’Œå·¥å…·é“¾æ¥
    anime:
      title: è¿½ç•ª
      subtitle: è®°å½•å’Œåˆ†äº«æˆ‘å–œæ¬¢çš„åŠ¨æ¼«ä½œå“
    project:
      title: é¡¹ç›®
      subtitle: å±•ç¤ºä¸€äº›ä¸ªäººæ­å»ºçš„é¡¹ç›®ï¼Œæ¬è¿å·¥ï¼
    music:
      title: éŸ³ä¹
      subtitle: æ²‰æµ¸å¼äº«å—éŸ³ä¹æ—¶å…‰
    moments:
      title: ç¬é—´
      subtitle: è®°å½•ç”Ÿæ´»çš„æ¯ä¸€ä»½ç‚¹ç‚¹æ»´æ»´
  menu:
    - id: home
      text: é¦–é¡µ
      href: /
      svg: material-symbols:home-outline-rounded
      target: _self
    - id: write
      text: å†™ä½œ
      href: /write
      svg: material-symbols:edit-square-outline-rounded
      target: _self
    - id: moments
      text: ç¬é—´
      href: /moments
      svg: material-symbols:camera-outline
      target: _self
    - id: navigation
      text: å¯¼èˆª
      href: /navigation
      svg: material-symbols:explore-outline
      target: _self
    - id: anime
      text: è¿½ç•ª
      href: /anime
      svg: material-symbols:movie-outline
      target: _self
    - id: music
      text: éŸ³ä¹
      href: /music
      svg: material-symbols:music-note-rounded
      target: _self
    - id: project
      text: é¡¹ç›®
      href: /project
      svg: material-symbols:code-blocks-outline
      target: _self
    - id: friend
      text: å‹äººå¸
      href: /friend
      svg: material-symbols:supervisor-account-outline-rounded
      target: _self
anime:
  bilibili:
    uid: '344681083'
  bangumi:
    uid: '670344'
  tmdb:
    apiKey: 93e1f2ac94622915e8088cca7361981d
    listId: '8627053'
github:
  owner: kobaridev
  repo: RyuChan
  branch: main
  appId: åœ¨éƒ¨ç½²ç«¯é…ç½®ç¯å¢ƒå˜é‡
  encryptKey: wudishiduomejimo
umami:
  enable: true
  baseUrl: https://umami.000.moe
  shareId: vd8qlxAvqAs6tE20
  websiteId: 99b08400-57e3-4fbc-89c7-95b22dd31bf2
  timezone: Asia/Shanghai
user:
  name: Miuna
  description: Cialloï½(âˆ ãƒ»Ï‰<)âŒ’â˜…
  site: https://blog.000.moe
  avatar: /images/uploads/1768632093006-5ozymr.jpg
  sidebar:
    social:
      - href: https://github.com/flhcxcat
        ariaLabel: Github
        title: Github
        svg: ri:github-line
      - href: https://space.bilibili.com/344681083
        ariaLabel: BiliBili
        title: BiliBili
        svg: ri:bilibili-line
      - href: https://steamcommunity.com/profiles/76561199513831368/
        ariaLabel: Steam
        title: Steam
        svg: ri:steam-line
      - href: fg24680s@gmail.com
        ariaLabel: Email
        title: Email
        svg: ri:mail-line
      - href: https://t.me/AzusaMoe
        ariaLabel: Telegram
        title: Telegram
        svg: ri:telegram-line
      - href: /rss.xml
        ariaLabel: RSS
        title: RSS
        svg: ri:rss-fill
  footer:
    social:
      - href: https://github.com/flhcxcat
        ariaLabel: Github
        title: Github
        svg: ri:github-line
      - href: https://space.bilibili.com/344681083
        ariaLabel: BiliBili
        title: BiliBili
        svg: ri:bilibili-line
      - href: https://steamcommunity.com/profiles/76561199513831368/
        ariaLabel: Steam
        title: Steam
        svg: ri:steam-line
      - href: fg24680s@gmail.com
        ariaLabel: Email
        title: Email
        svg: ri:mail-line
      - href: https://t.me/AzusaMoe
        ariaLabel: Telegram
        title: Telegram
        svg: ri:telegram-line
      - href: /rss.xml
        ariaLabel: RSS
        title: RSS
        svg: ri:rss-fill
comments:
  enable: true
  type: twikoo
  twikoo:
    envId: 'https://twikoo.000.moe/.netlify/functions/twikoo'

